# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# This workflow will install Deno then run `deno lint` and `deno test`.
# For more information see: https://github.com/denoland/setup-deno

        
name: Basic Workflow
on: [push]

jobs:
  k6_local_test:
    name: k6 local test run - basic example
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Run local k6 test
        uses: grafana/k6-action@v0.2.0
        with:
          filename: Scripts_de_Testes/K6_pap_teste_carga_performance.js
          flags: --out json=summary.json

      - name: Upload performance test results
        uses: actions/upload-artifact@v3
        with:
          name: k6-summary-report
          path: summary.json
          
